name: Test and Deploy

on:
  push:
    branches: [ dev ]
    paths:
      - 'price-lists-json/**'   #  Activar workflow si hay cambios en la carpeta 'price-lists-json' y subdirectorios
      # - 'scripts/deploy_updates.py' # (Opcional) Si cambios en el script deploy_updates.py también deben activar tests
      # - 'test/**'             # (Opcional) Si también quieres activar por cambios en tests (si tienes una carpeta 'test')
      # - 'requirements.txt'     # (Opcional) Si cambios en requirements también deben activar tests

  pull_request:
    branches: [ dev ]
    paths:
      - 'price-lists-json/**'   #  Mismos filtros que en 'push' para pull requests
      # - 'scripts/deploy_updates.py' # (Opcional) Mantener consistencia con 'push'
      # - 'test/**'             # (Opcional) Mantener consistencia con 'push'
      # - 'requirements.txt'     # (Opcional) Mantener consistencia con 'push'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest playwright
          playwright install chromium

      - name: Set Timezone to Buenos Aires
        run: |
          sudo timedatectl set-timezone America/Argentina/Buenos_Aires
          # Verificar que se cambió correctamente (opcional, pero útil para debugging)
          timedatectl status
      # -----------------------------------------------------

      - name: Wait for deployment propagation
        # Espera 60 segundos (ajusta el tiempo si es necesario)
        run: sleep 60

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Solo se ejecuta si los tests pasan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run deploy updates
        working-directory: ${{ github.workspace }} # <------------- ¡AÑADI ESTO!
        # Este script se encargará de eliminar el archivo _json_compres.gz y actualizar latest-json-filename.txt
        run: python scripts/deploy_updates.py
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_OWNER: ${{ secrets.GIT_OWNER }}
          GIT_REPO: ${{ secrets.GIT_REPO }}
          GIT_BRANCH: ${{ secrets.GIT_BRANCH }}
          GIT_FOLDER_PATH: price-lists-json # **VARIABLE DE ENTORNO CONFIGURANDO LA CARPETA**
