name: Test and Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest playwright
          playwright install

      - name: Wait for deployment propagation
        # Espera 30 segundos (ajusta el tiempo si es necesario)
        run: sleep 60

      - name: Run tests
        run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Solo se ejecuta si los tests pasan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run deploy updates
        # Este script se encargará de eliminar el archivo _json_compres.gz y actualizar latest-json-filename.txt
        run: python scripts/deploy_updates.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER: ${{ secrets.GITHUB_OWNER }}
          GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          GITHUB_BRANCH: ${{ secrets.GITHUB_BRANCH }}